name: Prepare Allure
description: Allure installation and folders
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install allure --fix-missing
        mkdir report
        mkdir report/allure-results
        mkdir report/allure-report
        mkdir report/allure-history
      shell: bash
