# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  fs-money:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/allure-prep
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
          dotnet restore money/fs-money.sln
      - name: Build
        run: |
          dotnet build --no-restore money/fs-money.sln
      - name: Test
        run: |
          dotnet test --no-build --verbosity normal money/fs-money.sln
      - name: Checking test results
        if: always()
        run: |
          pwd
          echo "report"
          ls report
          echo "report/allure-results"
          ls report/allure-results
      - uses: ./.github/actions/allure-upload
        if: always()
        with:
          folder-name: report/allure-results

  fs-syntax:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/allure-prep
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
          dotnet restore syntax/fs-syntax.sln
      - name: Build
        run: |
          dotnet build --no-restore syntax/fs-syntax.sln
      - name: Test
        run: |
          dotnet test --no-build --verbosity normal syntax/fs-syntax.sln
      - name: Checking test results
        if: always()
        run: |
          pwd
          echo "report"
          ls report
          echo "report/allure-results"
          ls report/allure-results
      - uses: ./.github/actions/allure-upload
        if: always()
        with:
          folder-name: report/allure-results

  allure:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - fs-money
      - fs-syntax
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # - name: Allure Report with history
      #   uses: simple-elf/allure-report-action@v1.5
      #   if: always()

      - name: Allure Report action from marketplace
        # uses: neonlabsorg/allure-report-action@master
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 25

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
